languageCode: "en-us"
baseUrl: "https://studioember.com"
title: "Studio Ember"
theme:
  - "override"
  - "hello-friend-ng"
paginate: 10
# disqusShortname: studioember # this just adds ads :/
googleAnalytics: UA-156727998-1
enableRobotsTXT: true

menu:
  main:
    - identifier: billsio
      name: Bills io
      title: Bills io
      url: /billsio/
      weight: 1
    - identifier: blog
      name: Blog
      title: Blog
      url: /posts/
      weight: 2
    - identifier: categories
      name: Categories
      title: Categories
      url: /categories/
      weight: 3
    - identifier: tags
      name: Tags
      title: Tags
      url: /tags/
      weight: 4

params:
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle: ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts: true

  # Enable sharing buttons, if you like
  enableSharingButtons: false

  # Metadata mostly used in document's head
  description: "My new homepage or blog"
  keywords: "blog"
  images: [""]
  customCSS:
    - "/css/override.css"
  logo:
    logoText: "studioember"

pygmentsCodefences: true
pygmentsStyle: "pygments"

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: dracula
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown