languageCode: "en-us"
baseUrl: "https://studioember.com"
title: "Studio Ember"
theme: "anubis"
paginate: 10
disqusShortname: studioember
googleAnalytics: UA-123-45
enableRobotsTXT: true

menu:
  main:
    - identifier: archive
      name: Archive
      title: Archive
      url: /posts/
      weight: 0    

params:
  author: "Nathan Grey"
  email: contact@studioember.com # used for microformats
  avatar: "/images/profile.jpeg" # used for microformats
  description: ""
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/override.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: false
  style: auto
  readMore: true
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  webmentions:
    url: https://yourdomain.com/webemntions/receive
    login: hugo-theme-anubis
    pingback: true

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown